# Generated by Django 3.0.8 on 2021-10-27 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(db_index=True, max_length=100, verbose_name='Деревня')),
                ('slag', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Деревня',
                'verbose_name_plural': 'Деревни',
                'ordering': ['village'],
            },
        ),
        migrations.CreateModel(
            name='Women',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slag', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Картинка')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обнавления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('vil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='women.Category', verbose_name='Деревня')),
            ],
            options={
                'verbose_name': 'Персонажи',
                'verbose_name_plural': 'Персонажи Наруто',
                'ordering': ['title'],
            },
        ),
    ]
